permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 闫肃
  email: 52macleo@gmail.com
  link: http://macleo.github.io
  weibo: http://weibo.com/
  github: http://github.com/macleo

# 站点信息
title: macleo的博客 
description: macleo的博客
url: http://macleo.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://macleo.github.io/images/shrek.png
favicon: http://yansu-uploads.stor.sinaapp.com/imgs/favicon.ico

# google analytics 设置
ga:
  id: UA-55659143-1
  url: macleo.github.io

# disqus 设置
disqus:
  shortname: macleo

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
